### ISSUE TITLE
st_usleep timeout granularity is in milliseconds

### ISSUE THREAD

**Issue by michaeltalyansky** [toffaletti/state-threads#3]
As a result, st_usleep(999) is equivalent to st_usleep(0).

Proposed solution:

```
diff --git a/event.c b/event.c
index 6ee32f7..f5ea4d9 100644
--- a/event.c
+++ b/event.c
@@ -1288,7 +1288,7 @@ ST_HIDDEN void _st_epoll_dispatch(void)

     /* Check for I/O operations */
     nfd = epoll_wait(_st_epoll_data->epfd, _st_epoll_data->evtlist,
-                     _st_epoll_data->evtlist_size, timeout);
+                     _st_epoll_data->evtlist_size, timeout == -1 ? -1 : 0);

     if (nfd > 0) {
         for (i = 0; i < nfd; i++) {
@@ -1359,6 +1359,14 @@ ST_HIDDEN void _st_epoll_dispatch(void)
             }
         }
     }
+    else if (nfd == 0) {
+       if (timeout >= 0) {
+           struct timespec t;
+           t.tv_sec = min_timeout / 1000000;
+           t.tv_nsec = min_timeout * 1000;
+           nanosleep(&t, NULL);
+       }
+    }
 }
```

**Comment by toffaletti** [comment]
I've found the timeout value for epoll_wait can't be depended on even for millisecond level granularity. Under moderate load there can be variation as much as 10 to 100ms between the timeout passed and how long the syscall actually takes. If you need microsecond level granularity, I've gotten better results using timerfd added to epoll fd set and a `-1` timeout to epoll_wait.

Your proposed solution doesn't really work because it doesn't take into account how long the epoll_wait syscall took, which can be microseconds.

**Comment by michaeltalyansky** [comment]
Thanks for the comments! Here is the problem I am having:

I have a state thread-per-connection proxy running in pthread P1; each state thread sends requests to a database serviced by a different pthread P2 via shared memory FIFO. After sending a request state thread blocks on a condition variable. Database pthread P2 sends back results via another FIFO; to pick up the results I have a special state thread inside P1 that polls the fifo (non-blocking), picks up any results, sets the results into corresponding state thread and signals the appropriate condition variable. When reply FIFO is drained, reply state thread goes into st_usleep.

Under light load, if requests are submitted sequentially, st_usleep suspends for at least 1 milli, so the theoretical maximum of the requests per second one pthread can process is 1000. I thought if I could reduce the sleep period to something like 250 micros, I could avoid this issue. In case of concurrency and more load, I understand that epoll_wait will not guarantee the delay precision, but it’s ok as long as the reply FIFO is drained before suspending – this will only affect latency of some requests but not throughput.

I can also try approach with the timerfd, thanks again for the suggestion and your comments!

**Comment by toffaletti** [comment]
What if your reply state thread polled an eventfd instead of using st_usleep to avoid busy spinning when the FIFO is empty? The database thread can signal the eventfd whenever it adds something to the FIFO. Depending on how you've implemented the FIFO, it might also be possible to only signal the eventfd when the FIFO was previously empty.

**Comment by michaeltalyansky** [comment]
Yes, I can signal eventfd only when the FIFO was previously empty, thanks for the suggestion!

Adding eventfd file descriptor to the epoll set and associating it with the state thread: is this something I can do through the existing API, or do I have to implement additional APIs?

**Comment by michaeltalyansky** [comment]
I guess,  st_netfd_open and read should do it, will try this tomorrow. Thanks!
